### ISSUE TITLE
Single apostrophes cause everything to be commented out

### ISSUE THREAD

**Issue by jcarn** [dude719/JetBrains-NASM-Language#12]
Unmatched apostrophes are causing everything between them to be commented out in green

**Comment by jcarn** [comment]
This is only a problem when the apostrophe is inside another comment

**Comment by ajkhoury** [comment]
It is not a comment. The dark green by default is a string. Unmatched apostrophes in NASM are not syntactically correct. Single apostrophes in NASM indicate a string. Comments in NASM are created by the semicolon (;) character. You can change the syntax color of strings  in Settings>Editor>Color Scheme>NASM. I haven't had any time lately to add anything to this project. Adding the ability to change the color of comments is super easy though.

**Comment by jcarn** [comment]
Understood, this project is super helpful by the way!
