### ISSUE TITLE
Plugin may be causing unresolved references in PyCharm

### ISSUE THREAD

**Issue by theY4Kman** [dude719/JetBrains-NASM-Language#19]
Source: https://youtrack.jetbrains.com/issue/PY-38880

With the NASM plugin installed on newer versions of PyCharm (including 2019.2.4 #PY-192.7142.42, and 2019.3 EAP #PY-193.4932.14), all method arguments appear as unresolved references.

![pycharm-unresolved-references-error-nasm](https://user-images.githubusercontent.com/33840/68318653-1de19a80-008b-11ea-87d3-de10d47aeaf6.png)

In the ticket, Andrew Butash found that disabling the NASM plugin fixes these unresolved references. I can confirm this, as well.

**Comment by ajkhoury** [comment]
I am very sorry this is happening. I'll look into this ASAP!

**Comment by ybroeker** [comment]
Same happens in IntelliJ Idea, all tags in every xml-file are reported.

<img width="662" alt="intellij_nasm" src="https://user-images.githubusercontent.com/11507418/68956278-06f82200-07c8-11ea-9b07-3640aceff6f9.png">

**Comment by ajkhoury** [comment]
This should be fixed by f4c3a8f, please let me know if you still run into unresolved references in v0.5.2
