### ISSUE TITLE
How do I run my assembly program?

### ISSUE THREAD

**Issue by rmaes4** [dude719/JetBrains-NASM-Language#2]

**Comment by ajkhoury** [comment]
Compile the assembly language files to object files using NASM, YASM, or FASM. Then you can link the object files to whatever target binary you want. 

Or you can use a CMake script that will do all that for you which is all integrated nicely in CLion.

Lastly, setup a Run/Debug Configuration to run/debug the compiled binary. 

I also recommend you go research some about compiling and linking with NASM, YASM, FASM, MASM, or any of the other assembly language compilers.
