### ISSUE TITLE
English grammer check

### ISSUE THREAD

**Issue by jorisrietveld** [dude719/JetBrains-NASM-Language#3]
Hi, first of all I want to say I am really enjoying this plugin. Would it be possible to enable the English grammar control?

**Comment by ajkhoury** [comment]
Do you mean adding Spellchecking support for the NASM language? If so, I'll look into it.

**Comment by jorisrietveld** [comment]
Yes, I was trying to find information about it and I think it could be added like this: https://stackoverflow.com/questions/12445117/intellij-idea-how-to-enable-spellchecking-for-custom-language-plugins

**Comment by jorisrietveld** [comment]
I added the spellchecker to the plugin and tested it. I am also looking if I could help implementing code completion but I have to learn more about jetbrains plugin system first. #4
