### ISSUE TITLE
[BITS 64] instruction isn't parsed correctly

### ISSUE THREAD

**Issue by GauthierPLM** [dude719/JetBrains-NASM-Language#8]
In the code bellow, instruction `[BITS 64]`is highlighed in red with the message "AsmTokenType.BLOCK_COMMENT or AsmTokenType.LINE_COMMENT is expected, got "BITS"".

However, it's a valid instruction that compiles without any problem

```asm
; strlen
;
; rdi -> const char * -> str

[BITS 64]
  global strlen

  section .text

strlen:
  xor rax, rax

count_char:
  cmp byte [rdi + rax], 0
  je end
  inc rax
  jmp count_char

end:
  ret
```

**Comment by ajkhoury** [comment]
Are you using the latest version? 
Perhaps you have an invalid unicode character near where the error occurs?

It parses fine for me. This is using the latest version 0.3-beta.3:

https://i.imgur.com/1Iow032.png

**Comment by ajkhoury** [comment]
I updated the Releases page with the most recent versions. Make sure you're using the latest version:

https://github.com/dude719/JetBrains-NASM-Language/releases/tag/v0.3-beta.3

**Comment by GauthierPLM** [comment]
Latest update indeed fix the problem. Thank you.
